# DigitalOcean's ubuntu droplet isn't up to date with installed packages, and on
# a fresh install I see 71 security upgrades available.
- name: Terminate any ongoing updates
  become: yes
  shell: killall apt apt-get
  ignore_errors: yes
  tags:
    - update
    - update-only

- name: System - apt update and apt upgrade
  apt: update_cache=yes upgrade=yes
  # SEE http://archive.vn/DKJjs#parameter-upgrade


- name: Install python
  become: yes
  apt:
    pkg:
      - python
      - python-pip
      - python3
      - python3-pip
    update_cache: yes
    cache_valid_time: 3600

- name: Install security tools
  become: yes
  apt:
    pkg:
      - ufw
      - fail2ban
      - unattended-upgrades
    update_cache: yes
    cache_valid_time: 3600

- name: Adjust APT update intervals
  copy:
    src: files/apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic

# Install psycopg2 to enable ansible postgreSQL features
- name: Installing psycopg2 dependencies
  become: yes
  apt:
    pkg:
      - libpq-dev

- name: Cloning psycopg2
  git:
    repo: https://github.com/psycopg/psycopg2.git
    dest: /tmp/psycopg2
    version: "2_8_6"
  become: yes

- name: psycopg2 - build
  shell:
    cmd: python setup.py build
    chdir: /tmp/psycopg2

- name: psycopg2 - install
  shell:
    cmd: python setup.py install
    chdir: /tmp/psycopg2
  become: yes

- name: System - Create services.slice
  template:
    src: files/services.slice.j2
    dest: /etc/systemd/system/services.slice

- name: System - systemd reload
  systemd: daemon_reload=yes
