- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/setup-system.yml

  vars_files:
    - ./vars.yml

  roles:
    - role: anxs.postgresql

  tasks:
    - name: Install non-Postgres extensions
      import_tasks: tasks/setup-misc.yml

    - name: Install Postgres extensions
      import_tasks: tasks/setup-extensions.yml

    - name: Adjust APT update intervals
      copy:
        src: files/apt_periodic
        dest: /etc/apt/apt.conf.d/10periodic

    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Allow connections to postgreSQL (5432)
      ufw:
        rule: allow
        port: "5432"

    - name: UFW - Deny all other incoming traffix by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    # reference
    # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html    
    - name: Add blocking of AWS instance metadata to UFW before rules
      become: yes
      shell:
        cmd: sed -i "/#\sdon't\sdelete\sthe\s'COMMIT'/ i -I OUTPUT 1 --proto tcp --destination 169.254.169.254 --match owner --uid-owner postgres --jump REJECT\n" /etc/ufw/before.rules

    - name: Setup logrotate for postgres logs
      copy:
        src: files/logrotate-postgres
        dest: /etc/logrotate.d/postgres

    # Install EC2 instance connect
    # Only for AWS images
    - name: install EC2 instance connect
      become: yes
      apt:
        pkg:
          - ec2-instance-connect
      tags:
        - aws-only
