name: CD

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Prime cache
        run: docker pull 727419036083.dkr.ecr.us-east-1.amazonaws.com/postgres-dev:latest
      - name: Build
        run: ./scripts/build.sh
      - name: Push
        run: ./scripts/push.sh